#!/bin/bash

rm -rf debug/

git pull

cd ~/Documents/git-repos/remote-github/data-extract-from-website

DATE_VAR=$(date +%F_%H:%M:%S)
LOG_FILE_NAME=$DATE_VAR-data-extract-from-website.log
PATH_TO_LOG_FILE=./logs/$LOG_FILE_NAME

mkdir -p logs
time ./extract-from-pick-a-part-helper DEBUG | tee $PATH_TO_LOG_FILE

