#!/bin/bash

cd ~/Documents/git-repos/remote-github/data-extract-from-website
git pull

# bare bones check that this script started:
DATE_VAR=$(date +%F_%H:%M:%S)
echo "DEBUG-$DATE_VAR" >> script_exec_started


# If there are no arguments, or the only argument is --email with a string after
# it, then we can continue...
if [[ -z "$1" || ( "$1" == "--cars-only" ) ]]
then

  mkdir -p temp
  cp * temp

  LOG_FILE_NAME=$DATE_VAR-data-extract-from-website.log
  PATH_TO_LOG_FILE=./logs/DEBUG-$DATE_VAR/$LOG_FILE_NAME

  mkdir -p logs
  mkdir -p logs/DEBUG-$DATE_VAR
  if [ "$1" == "--cars-only" ]
  then
    time ./extract-from-pick-a-part-helper DEBUG --cars-only | tee $PATH_TO_LOG_FILE
  else
    time ./extract-from-pick-a-part-helper DEBUG | tee $PATH_TO_LOG_FILE
  fi

  cp * logs/DEBUG-$DATE_VAR

  cp -f temp/* ./
  rm -rf temp

  cd logs/DEBUG-$DATE_VAR
  rm -rf debug-extract-from-pick-a-part
  rm -rf extract-from-pick-a-part
  rm -rf extract-from-pick-a-part-helper
  rm -rf names-of-items-on-webpage
  rm -rf README.md
  rm -rf script_exec_finish
  rm -rf script_exec_started


else
  echo " "
  echo "Usage: If no options are given, this script will run fully"
  echo "--cars-only : Will execute only the new car, or old car parts"
  echo " "
fi

# bare bones check that this script finished:
cd -
echo "DEBUG-$DATE_VAR" >> script_exec_finish

